var movie = "Avengers";
var isEntertaining = true;
movie = "A Quiet Place";
var num4 = 4;
var num6 = 6;
product = num4 * num6;
var favoriteFoods = ["Pizza", "Chips", "Sour Candy"];
favoriteFoods.shift();
// console.log(favoriteFoods);
console.log(movie.length);
